# Generated by Django 4.2 on 2023-05-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='gender',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='', max_length=30, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
