# Generated by Django 4.2 on 2023-05-21 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('publication_date', models.DateField(verbose_name='Fecha de publicación')),
                ('due_date', models.DateField(verbose_name='Fecha límite')),
                ('file', models.FileField(upload_to='assignments/', verbose_name='Archivo adjunto')),
                ('submitted', models.BooleanField(default=False, verbose_name='Enviado')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/', verbose_name='Archivo adjunto')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='Asignacion')),
            ],
        ),
        migrations.CreateModel(
            name='PatientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientgroup_patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientgroup_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment.patientgroup', verbose_name='Grupo'),
        ),
    ]
