# Generated by Django 4.2 on 2023-05-21 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_specialist', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('file', models.FileField(upload_to='material/', verbose_name='Archivo adjunto')),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repository.repository', verbose_name='Repositorio')),
            ],
        ),
    ]
